### ISSUE TITLE
E_ROUTE_NOT_FOUND

### ISSUE THREAD

**Issue by ratk** [RamonSilva20/adonis-starter#1]
on open in my browser i got this in log server 

HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/products/product-3-50.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/products/product-2-50.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/products/product-1-50.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/avatar/avatar-1.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/avatar/avatar-2.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/avatar/avatar-3.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/avatar/avatar-4.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/avatar/avatar-5.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/products/product-3-50.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/products/product-2-50.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/products/product-1-50.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/avatar/avatar-1.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/avatar/avatar-2.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/avatar/avatar-3.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/avatar/avatar-4.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)
HttpException: E_ROUTE_NOT_FOUND: Route not found GET /assets/img/avatar/avatar-5.png
    at Server._getRoute (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:146:13)
    at _executeServerMiddleware.then (D:\node\adonis-starter\node_modules\@adonisjs\framework\src\Server\index.js:429:28)

**Comment by RamonSilva20** [comment]
Just some image links there were not found, once removed the error message must fadeout.

**Comment by ratk** [comment]
ok thanks... and congratulations

Em qui, 12 de set de 2019 18:43, Ramon Silva <notifications@github.com>
escreveu:
